test 41

diff --git a/.github/workflows/check-json.yml b/.github/workflows/check-json.yml
--- a/.github/workflows/check-json.yml
+++ b/.github/workflows/check-json.yml
@@ -1,28 +1,29 @@
 name: Check JSON files
+
 on:
   pull_request:
     paths:
-      - 'ModConfigs/*/*/*.json'
+      - '**/*.json'
+      - '!**/lang/**/*.json'
 
 jobs:
-  json-lint:
-    name: JSON Lint
+  json_check:
     runs-on: ubuntu-latest
+
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+    - uses: actions/checkout@v2
+    - name: Set up Node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '14.x'
     - name: Install dependencies
+      run: npm ci
+    - name: Check JSON files
       run: |
-      sudo apt-get update -y && sudo apt-get install -y python3-pip
-      sudo pip3 install jsonlint jq
-    - name: Check JSON syntax
-      run: |
-        jsonlint -q ModConfigs/*/*/*.json || exit 1
-    - name: Check JSON structure
-      run: |
-        for file in ModConfigs/*/*/*.json; do
-          if ! jq -e '.[0].mods and .[0].desc and .[0].name and .[0].authors' $file > /dev/null; then
-            echo "JSON file $file does not contain the required parameters." >&2
+        npx jsonlint -q ./**/*.json
+        for f in $(git diff --name-only origin/main ${{ github.event.pull_request.head.sha }} --diff-filter=AM -- '**/*.json' -- ':!:**/lang/**/*.json'); do
+          if ! grep -q '"mods"\|mods\|desc\|name\|authors' "$f"; then
+            echo "The file $f does not contain the required parameters."
             exit 1
           fi
         done
